insert into clientes (nombre, apellido, email, create_at, foto) values ('Joserra', 'Lorenzo', 'joserra@correo.es', '2022-12-28', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Felipe', 'Pinillos', 'felipepi@correo.org','2022-12-23', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Pitita', 'Ridruejo', 'lapiti@correo.es', '2016-10-08', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Paco', 'Jones', 'pacojones@correo.org','2012-01-21', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Menganito', 'De Tal', 'elmengano@correo.es', '2013-07-12', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Fulanito', 'Matera', 'fultera@correo.org','2018-09-11', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Zutano', 'Biliario', 'elzuta@correo.es', '2005-03-30', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Camila', 'Pidación', 'cami@correo.org','2010-10-08', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Rosendo', 'Mesticado', 'rm@correo.es', '2014-05-20', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Gerardo', 'Mador', 'gerardomador@yahoo.es','2011-11-11', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Eustaquio', 'Ajenjo', 'eajenjo@ya.com', '1996-08-15', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Teodosio', 'Jones', 'teoj@gmail.net','2020-01-26', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Fulgencio', 'Criado', 'fc@jmail.es', '2016-11-10', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Samuel', 'Rulfo', 'samru@hotmail.es','2003-02-21', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Pituca', 'Marero', 'pituca@correo.es', '2022-12-28', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Lara', 'Mona', 'pechugona@correo.org','2016-05-03', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Pelayo', 'Camarena', 'peyo@inetum.es', '2014-04-06', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Ramón', 'Tículo', 'rmonti@elcorreo.es','2021-06-22', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Felipe', 'Lotas', 'fpelotas@ya.es', '2015-12-15', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Ester', 'Nera', 'eternera@kk.com','2022-10-11', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Marite', 'Re', 'lamaritere@correo.es', '2016-01-29', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Raimunda', 'Divosa', 'rda@mail.org','1999-08-14', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Genoveva', 'Liente', 'genova@cartas.es', '2002-02-02', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Inma', 'Culada', 'inmaculada@tengomail.net','2016-11-30', '');
insert into clientes (nombre, apellido, email, create_at, foto) values ('Sonia', 'De-Lama-Pineda', 'lasoni@misivas.com', '2010-03-16', '');